/* eslint no-magic-numbers: 0 */
import React, {useState} from 'react';
import {WellPlate} from '../lib';

const App = () => {
    const [state, setState] = useState({
        WellsData: [
            {wellId: 'A1', fileName: 'test 0'},
            {wellId: 'A2', fileName: 'test 1'},
            {wellId: 'A3', fileName: 'test 2'},
            {wellId: 'A4', fileName: 'test 3'},
            {wellId: 'A5', fileName: 'test 4'},
            {wellId: 'A6', fileName: 'test 5'},
            {wellId: 'A7', fileName: 'test 6'},
            {wellId: 'A8', fileName: 'test 7'},
            {wellId: 'A9', fileName: 'test 8'},
            {wellId: 'A10', fileName: 'test 9'},
            {wellId: 'A11', fileName: 'test 10'},
            {wellId: 'A12', fileName: 'test 11'},
            {wellId: 'B1', fileName: 'test 12'},
            {wellId: 'B2', fileName: 'test 13'},
            {wellId: 'B3', fileName: 'test 14'},
            {wellId: 'B4', fileName: 'test 15'},
            {wellId: 'B5', fileName: 'test 16'},
            {wellId: 'B6', fileName: 'test 17'},
            {wellId: 'B7', fileName: 'test 18'},
            {wellId: 'B8', fileName: 'test 19'},
            {wellId: 'B9', fileName: 'test 20'},
            {wellId: 'B10', fileName: 'test 21'},
            {wellId: 'B11', fileName: 'test 22'},
            {wellId: 'B12', fileName: 'test 23'},
            {wellId: 'C1', fileName: 'test 24'},
            {wellId: 'C2', fileName: 'test 25'},
            {wellId: 'C3', fileName: 'test 26'},
            {wellId: 'C4', fileName: 'test 27'},
            {wellId: 'C5', fileName: 'test 28'},
            {wellId: 'C6', fileName: 'test 29'},
            {wellId: 'C7', fileName: 'test 30'},
            {wellId: 'C8', fileName: 'test 31'},
            {wellId: 'C9', fileName: 'test 32'},
            {wellId: 'C10', fileName: 'test 33'},
            {wellId: 'C11', fileName: 'test 34'},
            {wellId: 'C12', fileName: 'test 35'},
            {wellId: 'D1', fileName: 'test 36'},
            {wellId: 'D2', fileName: 'test 37'},
            {wellId: 'D3', fileName: 'test 38'},
            {wellId: 'D4', fileName: 'test 39'},
            {wellId: 'D5', fileName: 'test 40'},
            {wellId: 'D6', fileName: 'test 41'},
            {wellId: 'D7', fileName: 'test 42'},
            {wellId: 'D8', fileName: 'test 43'},
            {wellId: 'D9', fileName: 'test 44'},
            {wellId: 'D10', fileName: 'test 45'},
            {wellId: 'D11', fileName: 'test 46'},
            {wellId: 'D12', fileName: 'test 47'},
            {wellId: 'E1', fileName: 'test 48'},
            {wellId: 'E2', fileName: 'test 49'},
            {wellId: 'E3', fileName: 'test 50'},
            {wellId: 'E4', fileName: 'test 51'},
            {wellId: 'E5', fileName: 'test 52'},
            {wellId: 'E6', fileName: 'test 53'},
            {wellId: 'E7', fileName: 'test 54'},
            {wellId: 'E8', fileName: 'test 55'},
            {wellId: 'E9', fileName: 'test 56'},
            {wellId: 'E10', fileName: 'test 57'},
            {wellId: 'E11', fileName: 'test 58'},
            {wellId: 'E12', fileName: 'test 59'},
            {wellId: 'F1', fileName: 'test 60'},
            {wellId: 'F2', fileName: 'test 61'},
            {wellId: 'F3', fileName: 'test 62'},
            {wellId: 'F4', fileName: 'test 63'},
            {wellId: 'F5', fileName: 'test 64'},
            {wellId: 'F6', fileName: 'test 65'},
            {wellId: 'F7', fileName: 'test 66'},
            {wellId: 'F8', fileName: 'test 67'},
            {wellId: 'F9', fileName: 'test 68'},
            {wellId: 'F10', fileName: 'test 69'},
            {wellId: 'F11', fileName: 'test 70'},
            {wellId: 'F12', fileName: 'test 71'},
            {wellId: 'G1', fileName: 'test 72'},
            {wellId: 'G2', fileName: 'test 73'},
            {wellId: 'G3', fileName: 'test 74'},
            {wellId: 'G4', fileName: 'test 75'},
            {wellId: 'G5', fileName: 'test 76'},
            {wellId: 'G6', fileName: 'test 77'},
            {wellId: 'G7', fileName: 'test 78'},
            {wellId: 'G8', fileName: 'test 79'},
            {wellId: 'G9', fileName: 'test 80'},
            {wellId: 'G10', fileName: 'test 81'},
            {wellId: 'G11', fileName: 'test 82'},
            {wellId: 'G12', fileName: 'test 83'},
            {wellId: 'H1', fileName: 'test 84'},
            {wellId: 'H2', fileName: 'test 85'},
            {wellId: 'H3', fileName: 'test 86'},
            {wellId: 'H4', fileName: 'test 87'},
            {wellId: 'H5', fileName: 'test 88'},
            {wellId: 'H6', fileName: 'test 89'},
            {wellId: 'H7', fileName: 'test 90'},
            {wellId: 'H8', fileName: 'test 91'},
            {wellId: 'H9', fileName: 'test 92'},
            {wellId: 'H10', fileName: 'test 93'},
            {wellId: 'H11', fileName: 'test 94'},
            {wellId: 'H12', fileName: 'test 95'},
        ],
    });
    const setProps = (newProps) => {
        setState(newProps);
    };

    return (
        <div>
            <WellPlate setProps={setProps} {...state} />
        </div>
    );
};

export default App;
